INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');


INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Mass Effect Trilogy é uma série de RPG de ação onde o comandante Shepard deve salvar a galáxia, enfrentando ameaças alienígenas e fazendo escolhas que moldam o destino galáctico.', 'Mass Effect Trilogy é uma série de jogos de RPG de ação desenvolvida pela BioWare. O jogador assume o papel do comandante Shepard, um herói intergaláctico em uma missão para salvar a galáxia da ameaça das máquinas sintéticas chamadas Reapers. A narrativa rica e envolvente permite escolhas que impactam o enredo, com foco em exploração espacial, batalhas táticas e alianças com diversas raças alienígenas. Com um forte desenvolvimento de personagens e decisões morais, a trilogia oferece uma experiência imersiva, combinando ação, estratégia e um profundo enredo de ficção científica.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Ambientado no Velho Oeste, Red Dead Redemption 2 segue Arthur Morgan, um fora da lei tentando sobreviver enquanto lida com lealdades e a decadência de sua gangue.', 'Red Dead Redemption 2 é um jogo de ação e aventura ambientado no final do século XIX. O protagonista, Arthur Morgan, faz parte da gangue Van der Linde, que luta para sobreviver à medida que a civilização avança no Velho Oeste. O jogo oferece um mundo aberto vasto, onde o jogador pode explorar, caçar, pescar e participar de atividades secundárias. Com um enredo emocionante sobre lealdade e redenção, Red Dead Redemption 2 é aclamado por sua narrativa imersiva, personagens profundos e gráficos impressionantes. É uma experiência única de vida no fim de uma era.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Em The Witcher 3, Geralt de Rivia, um caçador de monstros, busca sua filha adotiva enquanto enfrenta criaturas sobrenaturais e uma guerra devastadora em um mundo aberto imersivo.', 'The Witcher 3: Wild Hunt segue Geralt de Rivia, um caçador de monstros, em uma jornada épica para encontrar sua filha adotiva, Ciri, que está sendo perseguida pela caça selvagem. Situado em um mundo aberto, o jogo oferece uma narrativa rica, repleta de escolhas que impactam o desenrolar da história. Com combates táticos, exploração, e uma imersiva ambientação medieval, o jogo mistura mitologia eslava com fantasia. As missões secundárias também são complexas e profundas, tornando o universo de The Witcher um dos mais detalhados e envolventes dos jogos modernos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Sekiro: Shadows Die Twice é um jogo de ação e aventura onde o protagonista, um shinobi, busca vingança contra inimigos implacáveis em um Japão feudal cheio de perigos sobrenaturais.', 'Sekiro: Shadows Die Twice coloca o jogador na pele de um shinobi chamado Wolf, que deve resgatar seu mestre e buscar vingança contra uma série de inimigos mortais em um Japão feudal repleto de mistério e criaturas sobrenaturais. Com um sistema de combate preciso e desafiador, o jogo combina exploração e ação em um mundo vertical. A mecânica de "morrer e recomeçar" é central, com o jogo punindo e recompensando as escolhas dos jogadores. A narrativa é envolvente, e a dificuldade elevada oferece uma experiência única e gratificante para quem busca um verdadeiro desafio.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Em Ghost of Tsushima, Jin Sakai, um samurai, deve proteger sua ilha natal de uma invasão mongol, equilibrando a honra samurai e táticas furtivas para derrotar seus inimigos.', 'Ghost of Tsushima segue Jin Sakai, um samurai que luta para defender a ilha de Tsushima da invasão mongol no Japão feudal. Quando a honra samurai falha contra os invasores, Jin se adapta, adotando táticas furtivas e se tornando o "Fantasma". O jogo mistura combate de espada tradicional com técnicas de stealth e exploração em um mundo aberto impressionante, repleto de missões secundárias e atividades imersivas. O enredo é emocional, abordando temas de honra, sacrifício e identidade. A direção de arte, com seus lindos campos e paisagens, também é um destaque do título.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Super Mario World é um clássico jogo de plataforma onde Mario explora o Reino dos Dinossauros para resgatar a Princesa Peach, enfrentando inimigos e desafios em níveis coloridos e divertidos.', 'Super Mario World é um dos maiores clássicos dos jogos de plataforma, lançado para o Super Nintendo. O jogo segue Mario enquanto ele explora o Reino dos Dinossauros para salvar a Princesa Peach, enfrentando Bowser e seus seguidores. Com uma jogabilidade refinada, o jogo introduz novos itens e power-ups, como o Yoshi, que se tornou um dos personagens mais icônicos da franquia. Cada nível é repleto de desafios criativos, inimigos variados e segredos a serem descobertos, oferecendo uma experiência divertida e acessível para jogadores de todas as idades.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Hollow Knight é um jogo de ação e exploração em 2D, onde o jogador controla um cavaleiro em busca de respostas sobre a misteriosa terra de Hallownest, cheia de segredos e desafios.', 'Hollow Knight é um jogo de ação e exploração que se passa no subterrâneo repleto de criaturas e mistérios de Hallownest. O jogador controla um cavaleiro sem nome, enfrentando desafios enquanto descobre mais sobre a história de seu mundo perdido. Com uma jogabilidade desafiadora, combate fluido e uma atmosfera sombria, o jogo é um "metroidvania", com o jogador desbloqueando novas habilidades para explorar áreas antes inacessíveis. Com um design de níveis intrincado, belíssima arte e música envolvente, Hollow Knight é uma experiência profunda e imersiva que recompensa paciência e exploração.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Ori and the Blind Forest é um jogo de plataforma emocionalmente cativante, onde Ori, uma criatura espiritual, embarca em uma jornada para restaurar a floresta devastada e salvar seus amigos.', 'Ori and the Blind Forest é um jogo de plataforma e aventura com um enredo profundo e comovente. O jogo segue Ori, uma pequena criatura espiritual, que precisa restaurar a floresta de Nibel, devastada por uma tragédia. A jogabilidade combina exploração, resolução de quebra-cabeças e intensos desafios de plataforma, enquanto o jogador desbloqueia habilidades que permitem acessar novas áreas. Com gráficos deslumbrantes, uma trilha sonora emocionalmente envolvente e uma narrativa que toca o coração, Ori and the Blind Forest é uma experiência visual e emocionalmente rica, sendo aclamado tanto por sua jogabilidade quanto pela sua história.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead é um jogo de plataforma e ação inspirado em desenhos animados dos anos 1930, onde Cuphead e Mugman enfrentam desafiantes chefes em busca de resgatar suas almas.', 'Cuphead é um jogo de ação e plataforma que se destaca por seu estilo visual único, inspirado em desenhos animados dos anos 1930. O jogo segue Cuphead e Mugman enquanto eles enfrentam uma série de desafiantes chefes e inimigos, tentando resgatar suas almas perdidas após fazerem um pacto com o diabo. A jogabilidade é focada em combate de chefes com padrões complexos e uma dificuldade elevada. Com gráficos desenhados à mão, animação clássica e uma trilha sonora de jazz, Cuphead oferece uma experiência desafiadora e visualmente deslumbrante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic CD é um jogo de plataforma onde Sonic viaja no tempo para impedir os planos do Dr. Robotnik, enfrentando desafios em diferentes períodos do passado e futuro.', 'Sonic CD é um jogo de plataforma lançado para o Sega CD, onde Sonic precisa viajar através do tempo para impedir os planos do vilão Dr. Robotnik, que tenta dominar o futuro. O jogo introduz mecânicas de viagem no tempo, permitindo ao jogador alterar o curso da história ao visitar o passado, presente e futuro. Sonic deve resgatar os animais presos por Robotnik enquanto corre por níveis cheios de obstáculos e inimigos. Com sua velocidade característica, trilha sonora marcante e gráficos vibrantes, Sonic CD é um dos jogos mais inovadores da franquia.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);